version: '3.9'

services:
  database:
    image: ${DB_DOCKER_IMAGE}:${DB_DOCKER_IMAGE_TAG}
    ports:
      - ${DB_PORT}:${DB_DEFAULT_PORT}
    volumes:
      - mongodb-data-container:/data/db

volumes:
  mongodb-data-container:
